name: Compress images
on: push
jobs:
  build:
    name: calibreapp/webp-optimizer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: eucarlos/routes-crossroads-music-shop@master

      - name: Compress Images
        uses: calibreapp/webp-optimizer@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
